# Generated by Django 5.0.5 on 2024-05-09 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_facultad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datacore.facultad'),
            preserve_default=False,
        ),
    ]
