# Generated by Django 5.0.5 on 2024-06-06 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacore', '0003_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id_herramienta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='recurso',
            name='herramientas',
            field=models.ManyToManyField(to='datacore.herramienta'),
        ),
        migrations.CreateModel(
            name='Libreria',
            fields=[
                ('id_libreria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=50)),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacore.herramienta')),
            ],
        ),
    ]
