# Generated by Django 5.0.5 on 2024-06-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacore', '0004_herramienta_recurso_herramientas_libreria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='herramientas',
            field=models.ManyToManyField(blank=True, to='datacore.herramienta'),
        ),
    ]
