# Generated by Django 5.0.5 on 2024-06-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacore', '0006_recurso_direccion_ip_recurso_password_recurso_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='direccion_ip',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='user',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
