# Generated by Django 5.0.5 on 2024-06-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacore', '0007_alter_recurso_direccion_ip_alter_recurso_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ajustes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('valor', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
    ]
